#!/bin/bash
# =======================================================================
# Company:              Peer1
# Copyright(c):         Peer1 2008
# Project:              Kickstart 
# Code Devloper:        Carlos Avila <cavila@peer1.com>
#
# File Type:            Script
# File Name:            local_etch.ini                
# Description:          Start/stop/restart the provisioning system
# ======================================================================

PATH='/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin'
SCREENOPTS='-d -m -c /exports/kickstart/configs/screenrc'
SERVICES='dhcp3-server tftpd-hpa apache2 rsync samba postgresql-8.1 squid3 bind'
SCRIPTNAME='/etc/init.d/local'
DESC="Kickstart system"
NAME=`hostname`

if [ `id -u` -ne 0 ]; then
        echo -e "\n\tThis script should be run by root\n";
        exit 1;
fi

function start {

        for service in ${SERVICES} ; do
            echo "Starting $service"
            /etc/init.d/$service start
        done

        echo "Starting online audit"
        /exports/kickstart/cleanup/online_audit.pl doit
        echo "Configuring VLAN interfaces"
        /exports/kickstart/bin/vconf.pl
        echo "Generating DHCP configuration"
        /exports/kickstart/bin/dhcpconf.pl -f
        echo "Starting screen session"
        screen ${SCREENOPTS}
        echo "Starting the RapidReboot Log Daemon"
        /usr/bin/perl /exports/kickstart/bin/rapid_rebootd.pl
        echo "Enabling provisioning"
        /exports/kickstart/bin/ksctl on
        echo "Enabling dhcpd again to re-read conf file"
        /etc/init.d/dhcp3-server restart
        echo "Starting bind"
        /etc/init.d/bind restart

}

function stop {
        echo "Disabling provisioning"
        /exports/kickstart/bin/ksctl off

        echo "Killing screen session and RR Log daemon"
        for PID in `ps -ef | egrep -i "SCREEN ${SCREENOPTS}|rapid_rebootd.pl" | awk ' ! /grep/ {print $2}'` ; do
                kill -9 $PID
                if [ $? -eq 0 ] ; then
                        echo -e "\tsuccessfully killed pid $PID"
                else
                        echo -e "\tunable to kill pid $PID"
                fi
        done
        screen -wipe

        echo "Removing state files"
        for i in `ls /exports/kickstart/state/`; do
                echo -e "\tKilling ${i}... it should be dead already"
                kill -9 `cat /exports/kickstart/state/${i}`
                echo -e "\tRemoving ${i}"
                rm /exports/kickstart/state/${i}
        done
        echo "Done"

        for service in ${SERVICES} ; do
            echo "Stopping $service"
            /etc/init.d/$service stop
        done
}

case "$1" in

   stop)
        echo "Stopping $DESC: $NAME"
        stop
        echo  "Done"
        ;;

   restart)
        echo "Restarting $DESC: $NAME"
        stop
        start
        echo "Done"
        ;;

    start)
        echo "Starting $DESC: $NAME"
        start
        echo "Done"
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 0
        ;;
esac
