
-- configure out datacenter 
INSERT INTO sb_datacenter (id, name, dc_abbr) VALUES (1, 'London', 'LDN');


-- create our 1st vlan, sniff, sniff...it's so beautiful :)
INSERT INTO public.vlans (id, public_network, private_network) VALUES (405,'10.2.0.0/24','10.2.0.0/24');
-- Dummy vlan or else KS will break :( we are not using it in MH
INSERT INTO public.vlans (id, public_network, private_network) VALUES ( 122,'83.222.240.0/24','10.2.1.0/24');



