#!/bin/bash

cp -f /home/sbadmin/.ssh/id_dsa.pub ./etc/ssh/.sbadm_authorized_keys
cat /exports/bootimgs/sbrescue2.0/ssh_keys/* >>./etc/ssh/.sbadm_authorized_keys

chmod 600 ./etc/ssh/.sbadm_authorized_keys

tar --exclude 'Make' \
	--exclude 'CVS' \
	--exclude 'freebsd' \
	-zcvf /exports/installs/modules/sbadm.tgz \
	./etc/ssh/.sbadm_config \
	./etc/ssh/.sbadm_authorized_keys \
	./etc/init.d/sbadm

rm -f ./etc/ssh/.sbadm_authorized_keys
