#!/bin/sh -e
#
# S31nicsel - select the interface via pxe-injected kernel parameter

. /usr/share/debconf/confmodule

for i in $(cat /proc/cmdline); do
    case "$i" in
        BOOTIF=*)
            bootif_mac="$(echo ${i#BOOTIF=??-} | tr -s '-' ':')"
            for j in /sys/class/net/*; do
                if grep -q "${bootif_mac}" "${j}/address"; then
                    bootif_name="${j#/sys/class/net/}"
                    db_set netcfg/choose_interface "${bootif_name}"
                    exit 0
                fi
            done
        ;;
    esac
done