#!/bin/bash
#
# install-cpanel           This shell script enables the automatic install of cPanel
#
# Author:       cPanel Inc.
#
# chkconfig:    2345 99 01
#
# description:  Install cPanel if missing
# processname:  initinstall.static
#
# source function library
. /etc/rc.d/init.d/functions
lockfile=/var/lock/subsys/install-cpanel
RETVAL=0
start() {
    if ! ping -w 3 -c 2 -q httpupdate.cpanel.net > /dev/null; then
        echo -n "100% loss to httpupdate.cpanel.net.. restarting network"
        /sbin/service network restart
   fi

    echo -n \$"Starting cPanel Install: "
    if [ ! -e "/usr/sbin/install-cpanel" -o "`grep copyright /usr/sbin/install-cpanel`" = "" ]; then
        curl -o /usr/sbin/install-cpanel http://layer1.cpanel.net/initinstall.static
        chmod 700 /usr/sbin/install-cpanel
    fi
    touch "\$lockfile"
        /usr/sbin/install-cpanel && success || failure
        RETVAL=\$?
        echo
}
stop() {
        echo -n \$"Cleaning up cPanel Install: "
        rm -f "\$lockfile" && success || failure
        RETVAL=\$?
        echo
}
restart() {
        stop
        start
}
case "\$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|force-reload)
        restart
        ;;
  reload)
        ;;
  condrestart)
        [ -f "\$lockfile" ] && restart
        ;;
  status)
        if [ -f \$lockfile ]; then
                RETVAL=0
        else
                RETVAL=3
        fi
        ;;
  *)
        echo \$"Usage: \$0 {start|stop|status|restart|reload|force-reload|condrestart}"
        exit 1
esac
exit \$RETVAL