# $Id: Countries.sql,v 1.1 2002/03/03 01:11:39 jenni Exp $
#
# Table structure for table 'countries'
#

CREATE TABLE countries (
  countryid smallint(6) NOT NULL auto_increment,
  code char(4) NOT NULL default '',
  country char(40) NOT NULL default '',
  PRIMARY KEY  (countryid),
  KEY code (code,country)
) TYPE=MyISAM;

#
# Dumping data for table 'countries'
#

INSERT INTO countries VALUES (1,'AD','Andorra');
INSERT INTO countries VALUES (2,'AE','United Arab Emirates');
INSERT INTO countries VALUES (3,'AF','Afghanistan');
INSERT INTO countries VALUES (4,'AG','Antigua and Barbuda');
INSERT INTO countries VALUES (5,'AI','Anguilla');
INSERT INTO countries VALUES (6,'AL','Albania');
INSERT INTO countries VALUES (7,'AM','Armenia');
INSERT INTO countries VALUES (8,'AN','Netherlands Antilles');
INSERT INTO countries VALUES (9,'AO','Angola');
INSERT INTO countries VALUES (10,'AQ','Antarctica');
INSERT INTO countries VALUES (11,'AR','Argentina');
INSERT INTO countries VALUES (12,'AS','American Samoa');
INSERT INTO countries VALUES (13,'AT','Austria');
INSERT INTO countries VALUES (14,'AU','Australia');
INSERT INTO countries VALUES (15,'AW','Aruba');
INSERT INTO countries VALUES (16,'AZ','Azerbaijan');
INSERT INTO countries VALUES (17,'BA','Bosnia and Herzegovina');
INSERT INTO countries VALUES (18,'BB','Barbados');
INSERT INTO countries VALUES (19,'BD','Bangladesh');
INSERT INTO countries VALUES (20,'BE','Belgium');
INSERT INTO countries VALUES (21,'BF','Burkina Faso');
INSERT INTO countries VALUES (22,'BG','Bulgaria');
INSERT INTO countries VALUES (23,'BH','Bahrain');
INSERT INTO countries VALUES (24,'BI','Burundi');
INSERT INTO countries VALUES (25,'BJ','Benin');
INSERT INTO countries VALUES (26,'BM','Bermuda');
INSERT INTO countries VALUES (27,'BN','Brunei Darussalam');
INSERT INTO countries VALUES (28,'BO','Bolivia');
INSERT INTO countries VALUES (29,'BR','Brazil');
INSERT INTO countries VALUES (30,'BS','Bahamas');
INSERT INTO countries VALUES (31,'BT','Bhutan');
INSERT INTO countries VALUES (32,'BV','Bouvet Island');
INSERT INTO countries VALUES (33,'BW','Botswana');
INSERT INTO countries VALUES (34,'BY','Belarus');
INSERT INTO countries VALUES (35,'BZ','Belize');
INSERT INTO countries VALUES (36,'CA','Canada');
INSERT INTO countries VALUES (37,'CC','Cocos (Keeling) Islands');
INSERT INTO countries VALUES (38,'CF','Central African Republic');
INSERT INTO countries VALUES (39,'CG','Congo');
INSERT INTO countries VALUES (40,'CH','Switzerland');
INSERT INTO countries VALUES (41,'CI','Cote D\'Ivoire (Ivory Coast)');
INSERT INTO countries VALUES (42,'CK','Cook Islands');
INSERT INTO countries VALUES (43,'CL','Chile');
INSERT INTO countries VALUES (44,'CM','Cameroon');
INSERT INTO countries VALUES (45,'CN','China');
INSERT INTO countries VALUES (46,'CO','Colombia');
INSERT INTO countries VALUES (47,'CR','Costa Rica');
INSERT INTO countries VALUES (48,'CS','Czechoslovakia (former)');
INSERT INTO countries VALUES (49,'CU','Cuba');
INSERT INTO countries VALUES (50,'CV','Cape Verde');
INSERT INTO countries VALUES (51,'CX','Christmas Island');
INSERT INTO countries VALUES (52,'CY','Cyprus');
INSERT INTO countries VALUES (53,'CZ','Czech Republic');
INSERT INTO countries VALUES (54,'DE','Germany');
INSERT INTO countries VALUES (55,'DJ','Djibouti');
INSERT INTO countries VALUES (56,'DK','Denmark');
INSERT INTO countries VALUES (57,'DM','Dominica');
INSERT INTO countries VALUES (58,'DO','Dominican Republic');
INSERT INTO countries VALUES (59,'DZ','Algeria');
INSERT INTO countries VALUES (60,'EC','Ecuador');
INSERT INTO countries VALUES (61,'EE','Estonia');
INSERT INTO countries VALUES (62,'EG','Egypt');
INSERT INTO countries VALUES (63,'EH','Western Sahara');
INSERT INTO countries VALUES (64,'ER','Eritrea');
INSERT INTO countries VALUES (65,'ES','Spain');
INSERT INTO countries VALUES (66,'ET','Ethiopia');
INSERT INTO countries VALUES (67,'FI','Finland');
INSERT INTO countries VALUES (68,'FJ','Fiji');
INSERT INTO countries VALUES (69,'FK','Falkland Islands (Malvinas)');
INSERT INTO countries VALUES (70,'FM','Micronesia');
INSERT INTO countries VALUES (71,'FO','Faroe Islands');
INSERT INTO countries VALUES (72,'FR','France');
INSERT INTO countries VALUES (73,'FX','France, Metropolitan');
INSERT INTO countries VALUES (74,'GA','Gabon');
INSERT INTO countries VALUES (75,'GB','Great Britain (UK)');
INSERT INTO countries VALUES (76,'GD','Grenada');
INSERT INTO countries VALUES (77,'GE','Georgia');
INSERT INTO countries VALUES (78,'GF','French Guiana');
INSERT INTO countries VALUES (79,'GH','Ghana');
INSERT INTO countries VALUES (80,'GI','Gibraltar');
INSERT INTO countries VALUES (81,'GL','Greenland');
INSERT INTO countries VALUES (82,'GM','Gambia');
INSERT INTO countries VALUES (83,'GN','Guinea');
INSERT INTO countries VALUES (84,'GP','Guadeloupe');
INSERT INTO countries VALUES (85,'GQ','Equatorial Guinea');
INSERT INTO countries VALUES (86,'GR','Greece');
INSERT INTO countries VALUES (87,'GS','S. Georgia and S. Sandwich Isls.');
INSERT INTO countries VALUES (88,'GT','Guatemala');
INSERT INTO countries VALUES (89,'GU','Guam');
INSERT INTO countries VALUES (90,'GW','Guinea-Bissau');
INSERT INTO countries VALUES (91,'GY','Guyana');
INSERT INTO countries VALUES (92,'HK','Hong Kong');
INSERT INTO countries VALUES (93,'HM','Heard and McDonald Islands');
INSERT INTO countries VALUES (94,'HN','Honduras');
INSERT INTO countries VALUES (95,'HR','Croatia (Hrvatska)');
INSERT INTO countries VALUES (96,'HT','Haiti');
INSERT INTO countries VALUES (97,'HU','Hungary');
INSERT INTO countries VALUES (98,'ID','Indonesia');
INSERT INTO countries VALUES (99,'IE','Ireland');
INSERT INTO countries VALUES (100,'IL','Israel');
INSERT INTO countries VALUES (101,'IN','India');
INSERT INTO countries VALUES (102,'IO','British Indian Ocean Territory');
INSERT INTO countries VALUES (103,'IQ','Iraq');
INSERT INTO countries VALUES (104,'IR','Iran');
INSERT INTO countries VALUES (105,'IS','Iceland');
INSERT INTO countries VALUES (106,'IT','Italy');
INSERT INTO countries VALUES (107,'JM','Jamaica');
INSERT INTO countries VALUES (108,'JO','Jordan');
INSERT INTO countries VALUES (109,'JP','Japan');
INSERT INTO countries VALUES (110,'KE','Kenya');
INSERT INTO countries VALUES (111,'KG','Kyrgyzstan');
INSERT INTO countries VALUES (112,'KH','Cambodia');
INSERT INTO countries VALUES (113,'KI','Kiribati');
INSERT INTO countries VALUES (114,'KM','Comoros');
INSERT INTO countries VALUES (115,'KN','Saint Kitts and Nevis');
INSERT INTO countries VALUES (116,'KP','Korea (North)');
INSERT INTO countries VALUES (117,'KR','Korea (South)');
INSERT INTO countries VALUES (118,'KW','Kuwait');
INSERT INTO countries VALUES (119,'KY','Cayman Islands');
INSERT INTO countries VALUES (120,'KZ','Kazakhstan');
INSERT INTO countries VALUES (121,'LA','Laos');
INSERT INTO countries VALUES (122,'LB','Lebanon');
INSERT INTO countries VALUES (123,'LC','Saint Lucia');
INSERT INTO countries VALUES (124,'LI','Liechtenstein');
INSERT INTO countries VALUES (125,'LK','Sri Lanka');
INSERT INTO countries VALUES (126,'LR','Liberia');
INSERT INTO countries VALUES (127,'LS','Lesotho');
INSERT INTO countries VALUES (128,'LT','Lithuania');
INSERT INTO countries VALUES (129,'LU','Luxembourg');
INSERT INTO countries VALUES (130,'LV','Latvia');
INSERT INTO countries VALUES (131,'LY','Libya');
INSERT INTO countries VALUES (132,'MA','Morocco');
INSERT INTO countries VALUES (133,'MC','Monaco');
INSERT INTO countries VALUES (134,'MD','Moldova');
INSERT INTO countries VALUES (135,'MG','Madagascar');
INSERT INTO countries VALUES (136,'MH','Marshall Islands');
INSERT INTO countries VALUES (137,'MK','Macedonia');
INSERT INTO countries VALUES (138,'ML','Mali');
INSERT INTO countries VALUES (139,'MM','Myanmar');
INSERT INTO countries VALUES (140,'MN','Mongolia');
INSERT INTO countries VALUES (141,'MO','Macau');
INSERT INTO countries VALUES (142,'MP','Northern Mariana Islands');
INSERT INTO countries VALUES (143,'MQ','Martinique');
INSERT INTO countries VALUES (144,'MR','Mauritania');
INSERT INTO countries VALUES (145,'MS','Montserrat');
INSERT INTO countries VALUES (146,'MT','Malta');
INSERT INTO countries VALUES (147,'MU','Mauritius');
INSERT INTO countries VALUES (148,'MV','Maldives');
INSERT INTO countries VALUES (149,'MW','Malawi');
INSERT INTO countries VALUES (150,'MX','Mexico');
INSERT INTO countries VALUES (151,'MY','Malaysia');
INSERT INTO countries VALUES (152,'MZ','Mozambique');
INSERT INTO countries VALUES (153,'NA','Namibia');
INSERT INTO countries VALUES (154,'NC','New Caledonia');
INSERT INTO countries VALUES (155,'NE','Niger');
INSERT INTO countries VALUES (156,'NF','Norfolk Island');
INSERT INTO countries VALUES (157,'NG','Nigeria');
INSERT INTO countries VALUES (158,'NI','Nicaragua');
INSERT INTO countries VALUES (159,'NL','Netherlands');
INSERT INTO countries VALUES (160,'NO','Norway');
INSERT INTO countries VALUES (161,'NP','Nepal');
INSERT INTO countries VALUES (162,'NR','Nauru');
INSERT INTO countries VALUES (163,'NT','Neutral Zone');
INSERT INTO countries VALUES (164,'NU','Niue');
INSERT INTO countries VALUES (165,'NZ','New Zealand (Aotearoa)');
INSERT INTO countries VALUES (166,'OM','Oman');
INSERT INTO countries VALUES (167,'PA','Panama');
INSERT INTO countries VALUES (168,'PE','Peru');
INSERT INTO countries VALUES (169,'PF','French Polynesia');
INSERT INTO countries VALUES (170,'PG','Papua New Guinea');
INSERT INTO countries VALUES (171,'PH','Philippines');
INSERT INTO countries VALUES (172,'PK','Pakistan');
INSERT INTO countries VALUES (173,'PL','Poland');
INSERT INTO countries VALUES (174,'PM','St. Pierre and Miquelon');
INSERT INTO countries VALUES (175,'PN','Pitcairn');
INSERT INTO countries VALUES (176,'PR','Puerto Rico');
INSERT INTO countries VALUES (177,'PT','Portugal');
INSERT INTO countries VALUES (178,'PW','Palau');
INSERT INTO countries VALUES (179,'PY','Paraguay');
INSERT INTO countries VALUES (180,'QA','Qatar');
INSERT INTO countries VALUES (181,'RE','Reunion');
INSERT INTO countries VALUES (182,'RO','Romania');
INSERT INTO countries VALUES (183,'RU','Russian Federation');
INSERT INTO countries VALUES (184,'RW','Rwanda');
INSERT INTO countries VALUES (185,'SA','Saudi Arabia');
INSERT INTO countries VALUES (186,'Sb','Solomon Islands');
INSERT INTO countries VALUES (187,'SC','Seychelles');
INSERT INTO countries VALUES (188,'SD','Sudan');
INSERT INTO countries VALUES (189,'SE','Sweden');
INSERT INTO countries VALUES (190,'SG','Singapore');
INSERT INTO countries VALUES (191,'SH','St. Helena');
INSERT INTO countries VALUES (192,'SI','Slovenia');
INSERT INTO countries VALUES (193,'SJ','Svalbard and Jan Mayen Islands');
INSERT INTO countries VALUES (194,'SK','Slovak Republic');
INSERT INTO countries VALUES (195,'SL','Sierra Leone');
INSERT INTO countries VALUES (196,'SM','San Marino');
INSERT INTO countries VALUES (197,'SN','Senegal');
INSERT INTO countries VALUES (198,'SO','Somalia');
INSERT INTO countries VALUES (199,'SR','Suriname');
INSERT INTO countries VALUES (200,'ST','Sao Tome and Principe');
INSERT INTO countries VALUES (201,'SU','USSR (former)');
INSERT INTO countries VALUES (202,'SV','El Salvador');
INSERT INTO countries VALUES (203,'SY','Syria');
INSERT INTO countries VALUES (204,'SZ','Swaziland');
INSERT INTO countries VALUES (205,'TC','Turks and Caicos Islands');
INSERT INTO countries VALUES (206,'TD','Chad');
INSERT INTO countries VALUES (207,'TF','French Southern Territories');
INSERT INTO countries VALUES (208,'TG','Togo');
INSERT INTO countries VALUES (209,'TH','Thailand');
INSERT INTO countries VALUES (210,'TJ','Tajikistan');
INSERT INTO countries VALUES (211,'TK','Tokelau');
INSERT INTO countries VALUES (212,'TM','Turkmenistan');
INSERT INTO countries VALUES (213,'TN','Tunisia');
INSERT INTO countries VALUES (214,'TO','Tonga');
INSERT INTO countries VALUES (215,'TP','East Timor');
INSERT INTO countries VALUES (216,'TR','Turkey');
INSERT INTO countries VALUES (217,'TT','Trinidad and Tobago');
INSERT INTO countries VALUES (218,'TV','Tuvalu');
INSERT INTO countries VALUES (219,'TW','Taiwan');
INSERT INTO countries VALUES (220,'TZ','Tanzania');
INSERT INTO countries VALUES (221,'UA','Ukraine');
INSERT INTO countries VALUES (222,'UG','Uganda');
INSERT INTO countries VALUES (223,'UK','United Kingdom');
INSERT INTO countries VALUES (224,'UM','US Minor Outlying Islands');
INSERT INTO countries VALUES (225,'US','United States');
INSERT INTO countries VALUES (226,'UY','Uruguay');
INSERT INTO countries VALUES (227,'UZ','Uzbekistan');
INSERT INTO countries VALUES (228,'VA','Vatican City State (Holy See)');
INSERT INTO countries VALUES (229,'VC','Saint Vincent and the Grenadines');
INSERT INTO countries VALUES (230,'VE','Venezuela');
INSERT INTO countries VALUES (231,'VG','Virgin Islands (British)');
INSERT INTO countries VALUES (232,'VI','Virgin Islands (U.S.)');
INSERT INTO countries VALUES (233,'VN','Viet Nam');
INSERT INTO countries VALUES (234,'VU','Vanuatu');
INSERT INTO countries VALUES (235,'WF','Wallis and Futuna Islands');
INSERT INTO countries VALUES (236,'WS','Samoa');
INSERT INTO countries VALUES (237,'YE','Yemen');
INSERT INTO countries VALUES (238,'YT','Mayotte');
INSERT INTO countries VALUES (239,'YU','Yugoslavia');
INSERT INTO countries VALUES (240,'ZA','South Africa');
INSERT INTO countries VALUES (241,'ZM','Zambia');
INSERT INTO countries VALUES (242,'ZR','Zaire');
INSERT INTO countries VALUES (243,'ZW','Zimbabwe');
INSERT INTO countries VALUES (244,'COM','US Commercial');
INSERT INTO countries VALUES (245,'EDU','US Educational');
INSERT INTO countries VALUES (246,'GOV','US Government');
INSERT INTO countries VALUES (247,'INT','International');
INSERT INTO countries VALUES (248,'MIL','US Military');
INSERT INTO countries VALUES (249,'NET','Network');
INSERT INTO countries VALUES (250,'ORG','Non-Profit Organization');
INSERT INTO countries VALUES (251,'ARPA','Old style Arpanet');
INSERT INTO countries VALUES (252,'NATO','Nato field');

