# $Id: Time.sql,v 1.1 2002/03/03 02:38:12 jenni Exp $
#
# Table structure for table 'timezones'
#

CREATE TABLE timezones (
  zoneid smallint(6) NOT NULL auto_increment,
  name varchar(100) NOT NULL default '',
  offset float(4,1) NOT NULL default '0.0',
  dst char(1) NOT NULL default 'N',
  userid mediumint(9) NOT NULL default '0',
  PRIMARY KEY  (zoneid)
) TYPE=MyISAM;

#
# Dumping data for table 'timezones'
#

INSERT INTO timezones VALUES (1,'sydney',10.0,'S',0);
INSERT INTO timezones VALUES (2,'brisbane',10.0,'-',0);
INSERT INTO timezones VALUES (3,'perth',8.0,'-',0);
INSERT INTO timezones VALUES (4,'melbourne',10.0,'S',0);
INSERT INTO timezones VALUES (5,'mountain',-7.0,'N',0);
INSERT INTO timezones VALUES (6,'thornhill',-5.0,'N',0);
INSERT INTO timezones VALUES (7,'ontario',-5.0,'N',0);
INSERT INTO timezones VALUES (8,'toronto',-5.0,'N',0);
INSERT INTO timezones VALUES (9,'est',-5.0,'N',0);
INSERT INTO timezones VALUES (10,'edt',-5.0,'N',0);
INSERT INTO timezones VALUES (11,'eastern',-5.0,'N',0);
INSERT INTO timezones VALUES (12,'edmonton',-7.0,'N',0);
INSERT INTO timezones VALUES (13,'mst',-7.0,'N',0);
INSERT INTO timezones VALUES (14,'mdt',-7.0,'N',0);
INSERT INTO timezones VALUES (15,'newfoundland',-3.5,'N',0);
INSERT INTO timezones VALUES (867,'kingston',-5.0,'N',0);
INSERT INTO timezones VALUES (866,'adelaide',9.5,'N',0);
INSERT INTO timezones VALUES (865,'Zimbabwe',2.0,'-',0);
INSERT INTO timezones VALUES (864,'Zambia',2.0,'-',0);
INSERT INTO timezones VALUES (863,'Zaire Shaba',2.0,'-',0);
INSERT INTO timezones VALUES (862,'Zaire Kivu',2.0,'-',0);
INSERT INTO timezones VALUES (861,'Zaire Haut Zaire',2.0,'-',0);
INSERT INTO timezones VALUES (860,'Zaire Kinshasa Mbandaka',1.0,'-',0);
INSERT INTO timezones VALUES (859,'Zaire Kasai',2.0,'-',0);
INSERT INTO timezones VALUES (858,'Yugoslavia',1.0,'N',0);
INSERT INTO timezones VALUES (857,'Yemen',3.0,'-',0);
INSERT INTO timezones VALUES (856,'Windward Islands',-4.0,'-',0);
INSERT INTO timezones VALUES (855,'Wallis and Futuna Islands',12.0,'-',0);
INSERT INTO timezones VALUES (854,'Wales',0.0,'N',0);
INSERT INTO timezones VALUES (853,'Wake Island',12.0,'-',0);
INSERT INTO timezones VALUES (852,'Virgin Islands',-4.0,'-',0);
INSERT INTO timezones VALUES (851,'Vietnam',7.0,'-',0);
INSERT INTO timezones VALUES (850,'Venezuela',-4.0,'-',0);
INSERT INTO timezones VALUES (849,'Vatican City',1.0,'N',0);
INSERT INTO timezones VALUES (848,'Vanuatu',11.0,'N',0);
INSERT INTO timezones VALUES (847,'Uzbekistan',5.0,'-',0);
INSERT INTO timezones VALUES (846,'Uruguay',-3.0,'-',0);
INSERT INTO timezones VALUES (845,'USA Hawaii',-10.0,'-',0);
INSERT INTO timezones VALUES (844,'USA Aleutian',-10.0,'-',0);
INSERT INTO timezones VALUES (843,'USA Alaska',-9.0,'N',0);
INSERT INTO timezones VALUES (842,'USA Pacific',-8.0,'N',0);
INSERT INTO timezones VALUES (841,'USA Indiana East',-5.0,'-',0);
INSERT INTO timezones VALUES (840,'USA Arizona',-7.0,'-',0);
INSERT INTO timezones VALUES (839,'USA Mountain',-7.0,'N',0);
INSERT INTO timezones VALUES (838,'USA Eastern',-5.0,'N',0);
INSERT INTO timezones VALUES (837,'USA Central',-6.0,'N',0);
INSERT INTO timezones VALUES (836,'United Kingdom',0.0,'N',0);
INSERT INTO timezones VALUES (835,'United Arab Emirates',4.0,'-',0);
INSERT INTO timezones VALUES (834,'Ukraine',2.0,'N',0);
INSERT INTO timezones VALUES (833,'Uganda',3.0,'-',0);
INSERT INTO timezones VALUES (832,'Tuvalu',12.0,'-',0);
INSERT INTO timezones VALUES (831,'Turks and Caicos Islands',-5.0,'N',0);
INSERT INTO timezones VALUES (830,'Turkmenistan',5.0,'-',0);
INSERT INTO timezones VALUES (829,'Turkey',2.0,'N',0);
INSERT INTO timezones VALUES (828,'Tunisia',1.0,'-',0);
INSERT INTO timezones VALUES (827,'Tubuai Island',-10.0,'-',0);
INSERT INTO timezones VALUES (826,'Tuamotu Island',-10.0,'-',0);
INSERT INTO timezones VALUES (825,'Trinidad and Tobago',-4.0,'-',0);
INSERT INTO timezones VALUES (824,'Tonga',13.0,'-',0);
INSERT INTO timezones VALUES (823,'Togo',0.0,'-',0);
INSERT INTO timezones VALUES (822,'Thailand',7.0,'-',0);
INSERT INTO timezones VALUES (821,'Tanzania',3.0,'-',0);
INSERT INTO timezones VALUES (820,'Tajikistan',6.0,'-',0);
INSERT INTO timezones VALUES (819,'Taiwan',8.0,'-',0);
INSERT INTO timezones VALUES (818,'Tahiti',-10.0,'-',0);
INSERT INTO timezones VALUES (817,'Syria',2.0,'N',0);
INSERT INTO timezones VALUES (816,'Switzerland',1.0,'N',0);
INSERT INTO timezones VALUES (815,'Sweden',1.0,'N',0);
INSERT INTO timezones VALUES (814,'Swaziland',2.0,'-',0);
INSERT INTO timezones VALUES (813,'Suriname',-3.0,'-',0);
INSERT INTO timezones VALUES (812,'Sudan',2.0,'-',0);
INSERT INTO timezones VALUES (811,'St Vincent',-4.0,'-',0);
INSERT INTO timezones VALUES (810,'St Thomas',-4.0,'-',0);
INSERT INTO timezones VALUES (809,'St Pierre & Miquelon',-3.0,'N',0);
INSERT INTO timezones VALUES (808,'St Maarten',-4.0,'-',0);
INSERT INTO timezones VALUES (807,'St Lucia',-4.0,'-',0);
INSERT INTO timezones VALUES (806,'St Kitts Nevis',-4.0,'-',0);
INSERT INTO timezones VALUES (805,'St John',-4.0,'-',0);
INSERT INTO timezones VALUES (804,'St Helena',0.0,'-',0);
INSERT INTO timezones VALUES (803,'St Croix',-4.0,'-',0);
INSERT INTO timezones VALUES (802,'St Christopher',-4.0,'-',0);
INSERT INTO timezones VALUES (801,'Sri Lanka',5.5,'-',0);
INSERT INTO timezones VALUES (800,'Spain',1.0,'N',0);
INSERT INTO timezones VALUES (799,'South Africa',2.0,'-',0);
INSERT INTO timezones VALUES (798,'Somalia',3.0,'-',0);
INSERT INTO timezones VALUES (797,'Solomon Islands',11.0,'-',0);
INSERT INTO timezones VALUES (796,'Society Island',-10.0,'-',0);
INSERT INTO timezones VALUES (795,'Slovenia',1.0,'N',0);
INSERT INTO timezones VALUES (794,'Slovakia',1.0,'N',0);
INSERT INTO timezones VALUES (793,'Singapore',8.0,'-',0);
INSERT INTO timezones VALUES (792,'Sierra Leone',0.0,'-',0);
INSERT INTO timezones VALUES (791,'Seychelles',4.0,'-',0);
INSERT INTO timezones VALUES (790,'Senegal',0.0,'-',0);
INSERT INTO timezones VALUES (789,'Scotland',0.0,'N',0);
INSERT INTO timezones VALUES (788,'Saudi Arabia',3.0,'-',0);
INSERT INTO timezones VALUES (787,'Sao Tome e Principe',0.0,'-',0);
INSERT INTO timezones VALUES (786,'San Marino',1.0,'N',0);
INSERT INTO timezones VALUES (785,'Samoa',-11.0,'-',0);
INSERT INTO timezones VALUES (784,'Saba',-4.0,'-',0);
INSERT INTO timezones VALUES (783,'Rwanda',2.0,'-',0);
INSERT INTO timezones VALUES (782,'Russian Federation zone two',4.0,'N',0);
INSERT INTO timezones VALUES (781,'Russian Federation zone three',4.0,'N',0);
INSERT INTO timezones VALUES (780,'Russian Federation zone ten',11.0,'N',0);
INSERT INTO timezones VALUES (779,'Russian Federation zone six',7.0,'N',0);
INSERT INTO timezones VALUES (778,'Russian Federation zone seven',8.0,'N',0);
INSERT INTO timezones VALUES (777,'Russian Federation zone one',2.0,'N',0);
INSERT INTO timezones VALUES (776,'Russian Federation zone nine',10.0,'N',0);
INSERT INTO timezones VALUES (775,'Russian Federation zone four',5.0,'N',0);
INSERT INTO timezones VALUES (774,'Russian Federation zone five',6.0,'N',0);
INSERT INTO timezones VALUES (773,'Russian Federation zone eleven',12.0,'N',0);
INSERT INTO timezones VALUES (772,'Russian Federation zone eight',9.0,'N',0);
INSERT INTO timezones VALUES (771,'Romania',2.0,'N',0);
INSERT INTO timezones VALUES (770,'Reunion',4.0,'-',0);
INSERT INTO timezones VALUES (769,'Qatar',3.0,'-',0);
INSERT INTO timezones VALUES (768,'Puerto Rico',-4.0,'-',0);
INSERT INTO timezones VALUES (767,'Principe Island',0.0,'-',0);
INSERT INTO timezones VALUES (766,'Portugal',1.0,'N',0);
INSERT INTO timezones VALUES (765,'Ponape Island',11.0,'-',0);
INSERT INTO timezones VALUES (764,'Poland',1.0,'N',0);
INSERT INTO timezones VALUES (763,'Pingelap',12.0,'-',0);
INSERT INTO timezones VALUES (762,'Philippines',8.0,'-',0);
INSERT INTO timezones VALUES (761,'Peru',-5.0,'-',0);
INSERT INTO timezones VALUES (760,'Paraguay',-4.0,'N',0);
INSERT INTO timezones VALUES (759,'Papua New Guinea',10.0,'-',0);
INSERT INTO timezones VALUES (758,'Panama',-5.0,'-',0);
INSERT INTO timezones VALUES (757,'Palau',9.0,'-',0);
INSERT INTO timezones VALUES (756,'Pakistan',5.0,'-',0);
INSERT INTO timezones VALUES (755,'Oman',4.0,'-',0);
INSERT INTO timezones VALUES (754,'Norway',1.0,'N',0);
INSERT INTO timezones VALUES (753,'Northern Mariana Islands',10.0,'-',0);
INSERT INTO timezones VALUES (752,'Northern Ireland',0.0,'N',0);
INSERT INTO timezones VALUES (751,'Norfolk Island',11.5,'-',0);
INSERT INTO timezones VALUES (750,'Niue Island',-11.0,'-',0);
INSERT INTO timezones VALUES (749,'Nigeria',1.0,'-',0);
INSERT INTO timezones VALUES (748,'Niger',1.0,'-',0);
INSERT INTO timezones VALUES (747,'Nicaragua',-6.0,'N',0);
INSERT INTO timezones VALUES (746,'New Zealand',12.0,'N',0);
INSERT INTO timezones VALUES (745,'New Hebrides',11.0,'-',0);
INSERT INTO timezones VALUES (744,'New Caledonia',11.0,'-',0);
INSERT INTO timezones VALUES (743,'Nevis Montserrat',-4.0,'-',0);
INSERT INTO timezones VALUES (742,'Netherlands Antilles',-4.0,'-',0);
INSERT INTO timezones VALUES (741,'Netherlands',1.0,'N',0);
INSERT INTO timezones VALUES (740,'Nepal',5.8,'-',0);
INSERT INTO timezones VALUES (739,'Nauru Republic of',12.0,'-',0);
INSERT INTO timezones VALUES (738,'Namibia',1.0,'N',0);
INSERT INTO timezones VALUES (737,'Myanmar',6.5,'-',0);
INSERT INTO timezones VALUES (736,'Mozambique',2.0,'-',0);
INSERT INTO timezones VALUES (735,'Morocco',0.0,'-',0);
INSERT INTO timezones VALUES (734,'Mongolia',8.0,'-',0);
INSERT INTO timezones VALUES (733,'Monaco',1.0,'N',0);
INSERT INTO timezones VALUES (732,'Moldovian Rep Pridnestrovye',2.0,'N',0);
INSERT INTO timezones VALUES (731,'Moldova',2.0,'N',0);
INSERT INTO timezones VALUES (730,'Midway Island',-11.0,'-',0);
INSERT INTO timezones VALUES (729,'Mexico Sonora',-7.0,'-',0);
INSERT INTO timezones VALUES (728,'Mexico Sinaloa',-7.0,'-',0);
INSERT INTO timezones VALUES (727,'Mexico Nayarit',-7.0,'-',0);
INSERT INTO timezones VALUES (726,'Mexico Baja Calif Norte',-8.0,'N',0);
INSERT INTO timezones VALUES (725,'Mexico',-6.0,'-',0);
INSERT INTO timezones VALUES (724,'Melilla',1.0,'N',0);
INSERT INTO timezones VALUES (723,'Mayotte',3.0,'-',0);
INSERT INTO timezones VALUES (722,'Mauritius',4.0,'-',0);
INSERT INTO timezones VALUES (721,'Mauritania',0.0,'-',0);
INSERT INTO timezones VALUES (720,'Martinique',-4.0,'-',0);
INSERT INTO timezones VALUES (719,'Marshall Islands',12.0,'-',0);
INSERT INTO timezones VALUES (718,'Marquesas Islands',-9.5,'-',0);
INSERT INTO timezones VALUES (717,'Mariana Island',10.0,'-',0);
INSERT INTO timezones VALUES (716,'Malta',1.0,'N',0);
INSERT INTO timezones VALUES (715,'Mallorca Islands',1.0,'N',0);
INSERT INTO timezones VALUES (714,'Mali',0.0,'-',0);
INSERT INTO timezones VALUES (713,'Maldives',5.0,'-',0);
INSERT INTO timezones VALUES (712,'Malaysia',8.0,'-',0);
INSERT INTO timezones VALUES (711,'Malawi',2.0,'-',0);
INSERT INTO timezones VALUES (710,'Madeira',0.0,'N',0);
INSERT INTO timezones VALUES (709,'Madagascar',3.0,'-',0);
INSERT INTO timezones VALUES (708,'Macedonia',1.0,'N',0);
INSERT INTO timezones VALUES (707,'Luxembourg',1.0,'N',0);
INSERT INTO timezones VALUES (706,'Lithuania',2.0,'N',0);
INSERT INTO timezones VALUES (705,'Libya',2.0,'-',0);
INSERT INTO timezones VALUES (704,'Liberia',0.0,'-',0);
INSERT INTO timezones VALUES (703,'Lesotho',2.0,'-',0);
INSERT INTO timezones VALUES (702,'Leeward Islands',-4.0,'-',0);
INSERT INTO timezones VALUES (701,'Lebanon',2.0,'N',0);
INSERT INTO timezones VALUES (700,'Latvia',2.0,'N',0);
INSERT INTO timezones VALUES (699,'Laos',7.0,'-',0);
INSERT INTO timezones VALUES (698,'Kyrgyzstan',5.0,'N',0);
INSERT INTO timezones VALUES (697,'Kwajalein',-12.0,'-',0);
INSERT INTO timezones VALUES (696,'Kuwait',3.0,'-',0);
INSERT INTO timezones VALUES (695,'Kusaie',12.0,'-',0);
INSERT INTO timezones VALUES (694,'Korea Republic of',9.0,'-',0);
INSERT INTO timezones VALUES (693,'Korea Dem Republic of',9.0,'-',0);
INSERT INTO timezones VALUES (692,'Kiribati',12.0,'-',0);
INSERT INTO timezones VALUES (691,'Kenya',3.0,'-',0);
INSERT INTO timezones VALUES (690,'Kazakhstan',6.0,'N',0);
INSERT INTO timezones VALUES (689,'Jordan',2.0,'N',0);
INSERT INTO timezones VALUES (688,'Johnston Island',-10.0,'-',0);
INSERT INTO timezones VALUES (687,'Japan',9.0,'-',0);
INSERT INTO timezones VALUES (686,'Jamaica',-5.0,'-',0);
INSERT INTO timezones VALUES (685,'Italy',1.0,'N',0);
INSERT INTO timezones VALUES (684,'Israel',2.0,'N',0);
INSERT INTO timezones VALUES (683,'Ireland Republic of',0.0,'N',0);
INSERT INTO timezones VALUES (682,'Iraq',3.0,'N',0);
INSERT INTO timezones VALUES (681,'Iran',3.5,'-',0);
INSERT INTO timezones VALUES (680,'Indonesia West',7.0,'-',0);
INSERT INTO timezones VALUES (679,'Indonesia East',9.0,'-',0);
INSERT INTO timezones VALUES (678,'Indonesia Central',8.0,'-',0);
INSERT INTO timezones VALUES (677,'India',5.5,'-',0);
INSERT INTO timezones VALUES (676,'Iceland',0.0,'-',0);
INSERT INTO timezones VALUES (675,'Hungary',1.0,'N',0);
INSERT INTO timezones VALUES (674,'Hong kong',8.0,'-',0);
INSERT INTO timezones VALUES (673,'Honduras',-6.0,'-',0);
INSERT INTO timezones VALUES (672,'Haiti',-5.0,'N',0);
INSERT INTO timezones VALUES (671,'Guyana',-3.0,'-',0);
INSERT INTO timezones VALUES (670,'Guinea Bissau',0.0,'N',0);
INSERT INTO timezones VALUES (669,'Guinea',0.0,'-',0);
INSERT INTO timezones VALUES (668,'Guatemala',-6.0,'-',0);
INSERT INTO timezones VALUES (667,'Guam',10.0,'-',0);
INSERT INTO timezones VALUES (666,'Guadeloupe',-4.0,'-',0);
INSERT INTO timezones VALUES (665,'Grenadines',-4.0,'-',0);
INSERT INTO timezones VALUES (664,'Grenada',-4.0,'-',0);
INSERT INTO timezones VALUES (663,'Greenland Scoresbysun',-1.0,'N',0);
INSERT INTO timezones VALUES (662,'Greenland Thule',-4.0,'N',0);
INSERT INTO timezones VALUES (661,'Greenland',-3.0,'N',0);
INSERT INTO timezones VALUES (660,'Greece',2.0,'N',0);
INSERT INTO timezones VALUES (659,'Gibraltar',1.0,'N',0);
INSERT INTO timezones VALUES (658,'Ghana',0.0,'-',0);
INSERT INTO timezones VALUES (657,'Germany',1.0,'N',0);
INSERT INTO timezones VALUES (656,'Georgia',4.0,'-',0);
INSERT INTO timezones VALUES (655,'Gambier Island',-9.0,'-',0);
INSERT INTO timezones VALUES (654,'Gambia',0.0,'-',0);
INSERT INTO timezones VALUES (653,'Galapagos Islands',-5.0,'-',0);
INSERT INTO timezones VALUES (652,'Gabon',1.0,'-',0);
INSERT INTO timezones VALUES (651,'French Polynesia',-10.0,'-',0);
INSERT INTO timezones VALUES (650,'French Guiana',-3.0,'-',0);
INSERT INTO timezones VALUES (649,'France',1.0,'N',0);
INSERT INTO timezones VALUES (648,'Finland',2.0,'N',0);
INSERT INTO timezones VALUES (647,'Fiji',12.0,'-',0);
INSERT INTO timezones VALUES (646,'Faroe Island',0.0,'N',0);
INSERT INTO timezones VALUES (645,'Falkland Islands',-4.0,'N',0);
INSERT INTO timezones VALUES (644,'Ethiopia',3.0,'-',0);
INSERT INTO timezones VALUES (643,'Estonia',2.0,'N',0);
INSERT INTO timezones VALUES (642,'Eritrea',3.0,'-',0);
INSERT INTO timezones VALUES (641,'Equitorial Guinea',1.0,'-',0);
INSERT INTO timezones VALUES (640,'England',0.0,'N',0);
INSERT INTO timezones VALUES (639,'El Salvador',-6.0,'-',0);
INSERT INTO timezones VALUES (638,'Egypt',2.0,'N',0);
INSERT INTO timezones VALUES (637,'Ecuador',-5.0,'-',0);
INSERT INTO timezones VALUES (636,'Easter Island',-6.0,'N',0);
INSERT INTO timezones VALUES (635,'Dominican Republic',-4.0,'-',0);
INSERT INTO timezones VALUES (634,'Dominica',-4.0,'-',0);
INSERT INTO timezones VALUES (633,'Djibouti',3.0,'-',0);
INSERT INTO timezones VALUES (632,'Denmark',1.0,'N',0);
INSERT INTO timezones VALUES (631,'Dahomey',1.0,'-',0);
INSERT INTO timezones VALUES (630,'Czech Republic',1.0,'N',0);
INSERT INTO timezones VALUES (629,'Cyprus',2.0,'N',0);
INSERT INTO timezones VALUES (628,'Curacao',-4.0,'-',0);
INSERT INTO timezones VALUES (627,'Cuba',-5.0,'N',0);
INSERT INTO timezones VALUES (626,'Croatia',1.0,'N',0);
INSERT INTO timezones VALUES (625,'Cote d\'Ivoire',0.0,'-',0);
INSERT INTO timezones VALUES (624,'Costa Rica',-6.0,'-',0);
INSERT INTO timezones VALUES (623,'Cook Islands',-10.0,'-',0);
INSERT INTO timezones VALUES (622,'Congo',1.0,'-',0);
INSERT INTO timezones VALUES (621,'Colombia',-5.0,'-',0);
INSERT INTO timezones VALUES (620,'Cocos (Keeling) Islands',0.0,'N',0);
INSERT INTO timezones VALUES (619,'Christmas Islands',-10.0,'-',0);
INSERT INTO timezones VALUES (618,'China People\'s Rep',8.0,'-',0);
INSERT INTO timezones VALUES (617,'Chile',-4.0,'N',0);
INSERT INTO timezones VALUES (616,'Chatham Island',12.8,'N',0);
INSERT INTO timezones VALUES (615,'Channel Islands',0.0,'N',0);
INSERT INTO timezones VALUES (614,'Chad',1.0,'-',0);
INSERT INTO timezones VALUES (613,'Central African Rep',1.0,'-',0);
INSERT INTO timezones VALUES (612,'Cayman Islands',-5.0,'-',0);
INSERT INTO timezones VALUES (611,'Caroline Island',11.0,'-',0);
INSERT INTO timezones VALUES (610,'Cape Verde',-1.0,'-',0);
INSERT INTO timezones VALUES (609,'Canton Enderbury Islands',-11.0,'-',0);
INSERT INTO timezones VALUES (608,'Canary Islands',0.0,'N',0);
INSERT INTO timezones VALUES (607,'Canada Newfoundland',-3.5,'N',0);
INSERT INTO timezones VALUES (606,'Canada Atlantic',-4.0,'N',0);
INSERT INTO timezones VALUES (605,'Canada Yukon & Pacific',-8.0,'N',0);
INSERT INTO timezones VALUES (604,'Canada Mountain',-7.0,'N',0);
INSERT INTO timezones VALUES (603,'Canada Eastern',-5.0,'N',0);
INSERT INTO timezones VALUES (602,'Canada Central',-6.0,'N',0);
INSERT INTO timezones VALUES (601,'Cameroon',1.0,'-',0);
INSERT INTO timezones VALUES (600,'Cambodia',7.0,'-',0);
INSERT INTO timezones VALUES (599,'Burundi',2.0,'-',0);
INSERT INTO timezones VALUES (598,'Burkina Faso',0.0,'-',0);
INSERT INTO timezones VALUES (597,'Bulgaria',2.0,'N',0);
INSERT INTO timezones VALUES (596,'Brunei',8.0,'-',0);
INSERT INTO timezones VALUES (595,'British Virgin Islands',-4.0,'-',0);
INSERT INTO timezones VALUES (594,'Brazil West',-4.0,'N',0);
INSERT INTO timezones VALUES (593,'Brazil East',-3.0,'N',0);
INSERT INTO timezones VALUES (592,'Brazil Atlantic Islands',-1.0,'N',0);
INSERT INTO timezones VALUES (591,'Brazil Acre',-4.0,'N',0);
INSERT INTO timezones VALUES (590,'Botswana',2.0,'-',0);
INSERT INTO timezones VALUES (589,'Bosnia Hercegovina',1.0,'N',0);
INSERT INTO timezones VALUES (588,'Bonaire',-4.0,'-',0);
INSERT INTO timezones VALUES (587,'Bolivia',-4.0,'-',0);
INSERT INTO timezones VALUES (586,'Bhutan',6.0,'-',0);
INSERT INTO timezones VALUES (585,'Bermuda',-4.0,'N',0);
INSERT INTO timezones VALUES (584,'Benin',1.0,'-',0);
INSERT INTO timezones VALUES (583,'Belize',-6.0,'-',0);
INSERT INTO timezones VALUES (582,'Belgium',1.0,'N',0);
INSERT INTO timezones VALUES (581,'Belarus',2.0,'N',0);
INSERT INTO timezones VALUES (580,'Barbados',-4.0,'-',0);
INSERT INTO timezones VALUES (579,'Bangladesh',6.0,'-',0);
INSERT INTO timezones VALUES (578,'Balearic Islands',1.0,'N',0);
INSERT INTO timezones VALUES (577,'Bahrain',3.0,'-',0);
INSERT INTO timezones VALUES (576,'Bahamas',-5.0,'N',0);
INSERT INTO timezones VALUES (575,'Azores',-1.0,'N',0);
INSERT INTO timezones VALUES (574,'Azerbajian',3.0,'-',0);
INSERT INTO timezones VALUES (573,'Austria',1.0,'N',0);
INSERT INTO timezones VALUES (572,'Australia Western',8.0,'-',0);
INSERT INTO timezones VALUES (571,'Australia Tasmania',10.0,'N',0);
INSERT INTO timezones VALUES (570,'Australia South',9.5,'N',0);
INSERT INTO timezones VALUES (569,'Australia Australian Captial Territory',10.0,'N',0);
INSERT INTO timezones VALUES (568,'Australia Victoria',10.0,'N',0);
INSERT INTO timezones VALUES (567,'Australia Queensland',10.0,'-',0);
INSERT INTO timezones VALUES (566,'Australia New South Wales',10.0,'N',0);
INSERT INTO timezones VALUES (565,'Australia Lord Howe Island',10.5,'N',0);
INSERT INTO timezones VALUES (564,'Australia Northern Territory',9.5,'-',0);
INSERT INTO timezones VALUES (563,'Ascension',0.0,'-',0);
INSERT INTO timezones VALUES (562,'Aruba',-4.0,'-',0);
INSERT INTO timezones VALUES (561,'Armenia',4.0,'N',0);
INSERT INTO timezones VALUES (560,'Argentina western prov',-4.0,'-',0);
INSERT INTO timezones VALUES (559,'Argentina',-3.0,'-',0);
INSERT INTO timezones VALUES (558,'Antigua',-4.0,'-',0);
INSERT INTO timezones VALUES (557,'Antarctica',-2.0,'N',0);
INSERT INTO timezones VALUES (556,'Anguilla',-4.0,'-',0);
INSERT INTO timezones VALUES (555,'Angola',1.0,'-',0);
INSERT INTO timezones VALUES (554,'Andorra',1.0,'N',0);
INSERT INTO timezones VALUES (553,'American Samoa',-11.0,'-',0);
INSERT INTO timezones VALUES (552,'Algeria',1.0,'N',0);
INSERT INTO timezones VALUES (551,'Albania',1.0,'N',0);
INSERT INTO timezones VALUES (550,'Afghanistan',4.5,'-',0);
INSERT INTO timezones VALUES (868,'california',-8.0,'N',0);

