#!/bin/bash
# chkconfig: 2345 99 80
### BEGIN INIT INFO
# Provides: p1post
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start stop peer1 post configuration
# Description: p1post is the automated post installation
#              engine used for configuring servers.
### END INIT INFO

# File: p1post.init
# Package: p1post
# Install Location: /etc/init.d/p1post
# Name: p1post Init Script
#
# Supported Platforms: 
# Redhat Enterprise Linux Based Distributions (Fedora, CentOS, RHEL)
# Debian
# Ubuntu
#
# Description:
# This file facilitates the startup of p1post at startup.
#
# Usage:
# Under the root p1post development directory, you will find a script: "build.sh"
# Running this script will build the p1post RPM based upon this SPEC file.
#
# Author: Adam Hubscher <ahubscher AT peer1 DOT com>
# Version: 1.0
# Last Updated: N/A
# Revision: 1

# This script must be run as root
if [ $UID -ne 0 ]; then
	echo "This script must be run as root. Exiting." >&2
	exit 1
fi

# Start the postboot process
/usr/bin/screen -d -m /usr/local/p1post/p1post

# Remove ourselves from starting at boot time
[[ -f "/etc/redhat-issue" ]] && chkconfig --del p1post
[[ -f "/etc/debian_version" ]] && update-rc.d -f p1post remove

exit 0