#!/bin/bash

export CFG_RHN_USER="serverbeach"
export CFG_RHN_PASS="oxabgro46370"

grep $CFG_RHN_USER /etc/sysconfig/rhn/systemid >/dev/null

if [ $? -eq 0 ] ; then
    echo "Already upgraded"
else
#customer_id=$1
#customer_product_idnum=$2
    /usr/sbin/rhnreg_ks --force --username $CFG_RHN_USER --password $CFG_RHN_PASS --profilename $customers_id-$customer_product_idnum
fi
