#!/bin/bash
# This script must be run as root
if [ $UID -ne 0 ]; then
	echo "This script must be run as root. Exiting." >&2
	exit 1
fi

# Start the postboot process
/usr/bin/screen -d -m /usr/local/p1post/p1-postinstall.sh

# Remove ourselves from starting at boot time
rm -f /etc/rc3.d/S99p1post
rm -f /etc/rc2.d/S99p1post

exit 0