<HTML>
<HEAD>
    <TITLE>
        Manage Licenses
    </TITLE>
	<FRAMESET COLS="160,*" FRAMEBORDER="1" FRAMESPACING="2">
		<FRAME SRC="empty.html" NAME="left" ID="left" SCROLLING="Auto" MARGINWIDTH="0" MARGINHEIGHT="0" FRAMEBORDER=1></FRAME>
		<FRAME src="manage_licenses.php" name="content" FRAMEBORDER=1 SCROLLING="auto" MARGINWIDTH=0 MARGINHEIGHT=0></FRAME>
	</FRAMESET>
</HEAD>
<NOFRAMES>
<BODY>Frames Not Supported.</BODY>
</NOFRAMES>
</HTML>
