#!/bin/bash

set +e

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
CONTACT="PE (pesupport@peer1.com), PA (pa-dev@peer1.com)"
CUSTOMERS=(4 7000307)
PWD=$(/usr/bin/dirname $0)
is_customer_server=1

# Function that runs all of our post-install scripts.
run_scripts() {
	dir=$1
	cd $dir

	# Start executing scripts under our scripts directory
	for script in `ls -1 | sort` ; do
		
		# Some sort of work-around for updates on RHEL4/5
		[ $RHEL4UP -eq 1 ] && [ $script != '00rhel4up.sh' ] && continue;
		
		# Set our script to executable and run it.
		chmod +x $script
		echo "Running ${script}"
		postlog "INFO" "Running ${script}"
		./$script
		
		# Note our exit code from the script that was run.
		res=$?
	
		# Delete successful script if a customer server.
                # Done so support doesn't re-run the scripts.
                # In reality, we should write our scripts in 
                # scripts.d to handle being run more than once.
		if [ $res -eq 0 ] ; then
			# Only delete if a customer server
			if [ $is_customer_server -eq 1 ]; then
				rm -f ${script}
			fi
		# Catch any script failures.
		else
			echo "$script failed with status $res"
			postlog "FATAL" "$script failed with status $res"
			echo "$script $res" >> "${p1post}/failed"
		fi
	done
}



# Source any files under 'lib'
for lib in `find ${PWD} | grep lib`; do
	[ -f ${lib} ] && . "$lib"
done

export PATH SCRIPT_D p1post

# Hopefully ${p1post} is defined in sbks_lib.sh!
. "${p1post}/postconf.info"

# the two functions export MACADDR and IPADDR
getMAC
getIP

# Determine if we are running on a customer server or known test server
if [ -z "$customer_numbger" ]; then
	for customer in ${CUSTOMERS[@]}; do
		if [ $customer_number -ne $customer ]; then
			continue
		else
			postMsg="This appears to be a TEST (${customer}) server."
			postMsg="${postMsg} Not deleting p1post directory."
			echo ${postMsg}
			postlog "INFO" "${postMsg}"
			is_customer_server=0
			break
		fi
	done
else
	postMsg="\$customer_number not set. We will remove the p1post directory"
	echo ${postMsg}
	postlog "INFO" "${postMsg}"
fi

# Create file to write failures from above function
# Also creates a running file, but we do not log to it. 
echo -n > "${p1post}/failed"
echo -n > "${p1post}/running"

# Make sure we have network connectivity.
retries=0
res=0
while [ $retries -lt 5 ] && [ $res -ne 0 ]; do
	ping -c1 -i5 ${ks_public_ipaddr}
	res=$?
	retries=$(($retries + 1))
	echo "Tried to reach kickstart $retries time(s)"
	postlog "INFO" "Tried to reach kickstart $retries time(s)"

	echo "Server IP is $IPADDR"
	postlog "INFO" "Server IP is $IPADDR"

	echo "Sleeping for a bit..."
	postlog "INFO" "Sleeping for a bit..."
	sleep 2
done
if [ $res -ne 0 ] ; then
	echo "Cannot contact kickstart server, possible network problem."
	echo "Check that the server has not been moved to the wrong VLAN."
	echo "If the server appears to be on the proper VLAN, this is"
	echo "probably a network problem."
	echo
	echo -n "Press any key to continue .. "
	read FOO
fi

# If we have connectivity, tell Kickstat we're in postboot
fetch "http://${ks_public_ipaddr}/cgi-bin/register.cgi" \
	"macaddr=${MACADDR}&ipaddr=${IPADDR}&status=postboot"

postMsg="Syncing hardware clock to time.nist.gov"
echo ${postMsg}
postlog "INFO" "${postMsg}"
ntpdate -u -b time.nist.gov
hwclock --systohc

postMsg="Restarting time-dependent services"
echo ${postMsg}
postlog "INFO" "${postMsg}"
service crond restart
service syslog restart

# CPanel b0rks the resolv.conf
cp -f /etc/resolv.conf /etc/resolv.conf.SB

# Run our postboot scripts if present.
if [ -d "${p1post}/script.d" ] ; then
	postMsg="Running postboot scripts in ${p1post}/script.d"
	echo ${postMsg}
	postlog "INFO" "${postMsg}"
	run_scripts "${p1post}/script.d"
else
	postMsg="No postboot scripts present. Skipping."
	echo ${postMsg}
	postlog "INFO" "No postboot scripts present. Skipping."
fi

# If ${p1post}/failed has anything in it, set status to failed.
if [ -s "${p1post}/failed" ] ; then
	STATUS="ksfail"
else
	STATUS="kickstarted"
fi

# Restore our resolv.conf from the cPanel issue
cp -f /etc/resolv.conf.SB /etc/resolv.conf

# Report back to the kickstart server
fetch "http://${ks_public_ipaddr}/cgi-bin/register.cgi" \
	"macaddr=${MACADDR}&ipaddr=${IPADDR}&status=${STATUS}"

# Cleanup time!
echo -n > /var/log/wtmp
rm -f /root/.bash_history
rm -f /home/beach/.bash_history

# If status is kickstarted (completed) and this is a customer server
# proceed with the cleanup of the system.
if [ "${STATUS}" == "kickstarted" ] ; then
	# Add ONLINE=*unix time* to /boot/.serverbeach so we know when it finished
	online=`date "+%s"`
	echo "ONLINE=$online" >> /boot/.serverbeach

	# Keep the following around if this is a dev server.
        if [ $is_customer_server -eq 1 ] ; then
	        rm -f /etc/resolv.conf.new
	        rm -rf ${p1post}
	        rm -f /tmp/postconf.txt
	        rm -f $0

		# Remove installer and error logs
		rm -f /root/anaconda-ks.cfg
		rm -f /root/install.log
		rm -f /root/install.log.syslog
		rm -f /var/log/lasterror
	fi

	# @2010-06-16 hdawood Per bprewit and dmoore, to avoid FS corruption, we do
	# sync()'s to flush memory to disk before RR kicks in
	halt -fh
else
	# If status is not kickstarted, stop so it can be troubleshot.
	echo "Something went wrong when trying to run $0"
	echo "Please check and report the contents of ${p1post}/failed and"
	echo "${postboot_log} to ${CONTACT}..."
	read FOO
	exit 1
fi

exit 0
