<html>
<head>
<title>CORE</title>
</head>
<body style="padding: 2ex">

<p style="font-size: x-large; background: #CFC; text-align: center; margin-left: 20%; margin-right: 20%">
CORE is experiencing temporary technical difficulties
</p>

<p style="width: 60ex; text-align: center; margin-left: auto; margin-right: auto">
If you try your command again, it should work.  If you get this page a second time, then please file a bug.
</p>

<p style="color: black; display: table; margin-left: auto; padding: 1ex; margin-top: 10ex; font-size: small">
Generated by <b>CORE</b> on
<?php
print (strftime ("%c"));
?>
</p>

</body>

</html>
